[build]
  command = "npx prisma generate && npx prisma db push && next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"

# Handle API routes and dynamic routes
[[redirects]]
  from = "/v/*"
  to = "/v/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200
